const list = [
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "256302",
        name: "Chettinad Food House",
        uuid: "c8662c30-c6b6-46a3-8048-0b6ed397cc37",
        city: "1",
        area: "Btm Layout",
        totalRatingsString: "",
        cloudinaryImageId: "kdpo4hc0gii1sciupi3x",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        slaString: "31 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "chettinad-food-house-btm-btm",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Jai Bheema Nagar",
        parentId: 21165,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        menu: [
          {
            title: "King Samosa",
            price: 65,
            description: "Somasa filled with potatoes and peas!",
          },    {
            title: "Gulab jamun",
            price: 85,
            description: "Sweetest",
          },
        ],
        aggregatedDiscountInfo: {
          header: "10% off",
          shortDescriptionList: [
            {
              meta: "10% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "10% off up to ₹40 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "10% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "10% off up to ₹40 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 8600,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8600,
          message: "",
          title: "Delivery Charge",
          amount: "8600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.7 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=256302&source=collection&query=Idli",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          lastMileTravel: 0,
          lastMileDistance: 7.7,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "268053",
        name: "Breakfast Wala",
        uuid: "7aaec98e-5a75-4166-adbf-4b62bad8f492",
        city: "1",
        area: "Indiranagar",
        totalRatingsString: "",
        cloudinaryImageId: "nqqgaewevlqedkhlirgc",
        cuisines: ["North Indian"],
        tags: [],
        menu: [
          {
            title: "Suji Kheer",
            price: 265,
            description: "With added Kesar",
          },    {
            title: "Gulab Jamun 1 Piece",
            price: 48,
            description: "Sweet and Aromatic",
          },
        ],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 59,
        minDeliveryTime: 59,
        maxDeliveryTime: 59,
        slaString: "59 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "breakfast-express-indiranagar-indiranagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "1st Stage",
        parentId: 387373,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "50% off",
          shortDescriptionList: [
            {
              meta: "50% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "50% off up to ₹100 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "50% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "50% off up to ₹100 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 7600,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7600,
          message: "",
          title: "Delivery Charge",
          amount: "7600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "6.6 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=268053&source=collection&query=Idli",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 59,
          minDeliveryTime: 59,
          maxDeliveryTime: 59,
          lastMileTravel: 0,
          lastMileDistance: 6.6,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "463366",
        name: "Amma's Andra stlye Homely Food",
        uuid: "720bfeb3-1f5f-4338-affd-d01a5887e7d8",
        city: "1",
        area: "Basaveshwaranagar",
        totalRatingsString: "",
        cloudinaryImageId: "gqsqqfegmdnfcwzrexwh",
        cuisines: ["Biryani", "North Indian"],
        tags: [],
        menu: [
          {
            title: "Masala Dosa",
            price: 65,
            description: "Comes with Sambar and cocunut chutney!",
          },    {
            title: "Ghee Masala Dosa",
            price: 85,
            description: "Comes with Sambar and cocunut chutney!",
          },
        ],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 46,
        minDeliveryTime: 46,
        maxDeliveryTime: 46,
        slaString: "46 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant:
            "amma's-andra-stlye-homely-food-basaveshwaranagar-basaveshwaranagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "4th block",
        parentId: 277946,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "BASE_DISTANCE",
              fee: 8600,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8600,
          message: "",
          title: "Delivery Charge",
          amount: "8600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.6 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=463366&source=collection&query=Idli",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 46,
          minDeliveryTime: 46,
          maxDeliveryTime: 46,
          lastMileTravel: 0,
          lastMileDistance: 7.6,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "256304",
        name: "Rasmeet Food",
        uuid: "c8662c30-c6b6-46a3-8048-0b6ed397cc37",
        city: "1",
        area: "Btm Layout",
        totalRatingsString: "",
        cloudinaryImageId: "kdpo4hc0gii1sciupi3x",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        slaString: "31 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "chettinad-food-house-btm-btm",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Jai Bheema Nagar",
        parentId: 21165,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        menu: [
          {
            title: "Masala Dosa",
            price: 65,
            description: "Comes with Sambar and cocunut chutney!",
          },    {
            title: "Ghee Masala Dosa",
            price: 85,
            description: "Comes with Sambar and cocunut chutney!",
          },
        ],

        chain: [],

        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.7 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=256302&source=collection&query=Idli",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          lastMileTravel: 0,
          lastMileDistance: 7.7,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
];

export default list;
